### ISSUE TITLE
نمایش نادرست اطلاعات روی نمایشگر

### ISSUE THREAD

**Issue by mamalli11** [ErfanRo/ESP8266clock#1]
سلام کدی که شما نوشته اید من آپلود کردم روی esp ولی نمایشگر اطلاعات را به این صورت نمایش میدهد 
و اینکه لطف کنید و مشخص کنید اتصالات LED ها را به کدام پایه ها متصل کنیم 

![5-49-15](https://github.com/user-attachments/assets/2a305065-2f69-40e4-aabe-ca7e7b1bc189)

**Comment by ErfanRo** [comment]
نمایشگر شما ssd1306. هستش ؟ 
Led ws2812 به D5 وصل میشه

**Comment by mamalli11** [comment]
بله من با 3 عدد نمایشگر با ابعاد مختلف هم تست کردم همین مشکل که در تصویر بالا هست را داشتم

**Comment by ErfanRo** [comment]
![IMG_20241119_113943.jpg](https://github.com/user-attachments/assets/0134ed74-38c2-4a4b-bd26-c2cc024fbb54)

من دوباره کد رو اپلود کردم و مشکلی نداره . 
حتماً باید از نسخه ۲.۶ کتابخونه خود esp استفاده بشه .![IMG_20241119_114137.jpg](https://github.com/user-attachments/assets/297d141c-aa42-45ea-8040-c77453a7d31e)

**Comment by mamalli11** [comment]
سپاسگذارم از راهنماییتون مشکل حل شد
